apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdl-ppml-notebook
  namespace: bigdl-ppml-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigdl-ppml-notebook
  template:
    metadata:
      name: bigdl-ppml-notebook
      labels:
        app: bigdl-ppml-notebook
    spec:
      containers:
      - name: bigdl-ppml-notebook
        image: {{ .Values.imageName }}
        command: [ "/ppml/jupyter/examples/start-notebook.sh" ]
        ports:
        - containerPort: {{ .Values.jupyterPort }}
          hostPort: {{ .Values.jupyterPort }}
        env:
        - name: RUNTIME_K8S_SPARK_IMAGE
          value: {{ .Values.imageName }}
        - name: nfs_server_ip
          value: {{ .Values.nfsServerIp }}
        - name: nfs_path
          value: {{ .Values.nfsPath }}
        - name: SGX_ENABLED
        {{- if or (eq .Values.TEEMode "tdx") (eq .Values.TEEMode "native") }}
          value: "false"
        {{- else }}
          value: "true"
        {{- end }}
        - name: JUPYTER_PORT
          value: "{{ .Values.jupyterPort }}"
        volumeMounts:
        - name: nfs-storage
          mountPath: /ppml/jupyter/example
        - name: kubeconfig
          mountPath: /root/.kube
      {{- if eq .Values.TEEMode "sgx" }}
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: aesm-socket
          mountPath: /var/run/aesmd/aesm.socket
      resources:
          requests:
            cpu: 8
            memory: 32Gi
            sgx.intel.com/epc: 34359738368
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
          limits:
            cpu: 10
            memory: 40Gi
            sgx.intel.com/epc: 34359738368
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
      {{- end }}
      volumes:
      - name: nfs-storage
        nfs:
          server: {{ .Values.nfsServerIp }}
          path: {{ .Values.nfsPath }}
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
      {{- if eq .Values.TEEMode "sgx" }}
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: aesm-socket
        hostPath:
          path: /var/run/aesmd/aesm.socket
      {{- end }}

